### ISSUE TITLE
[com_menus]  'UnexpectedValueException' with %ss::moveByReference() when making a child of itself

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15140]
### Steps to reproduce the issue
Create an Administrator menu.
Create a menu item under this Administrator menu.
Click `Save & Copy` button.
Click `Check All` button.
Click `Batch` button.
Click this menu item under `- Don't copy or move-` dropdown.
Click the `Move` radio button.
Click `Process` button.

A warning message is displayed:
```
Batch process failed with following error: exception 'UnexpectedValueException' with message '%ss::moveByReference() is trying to make record ID 489 a child of itself.' in C:\xampp\htdocs\joomla-cms-staging\libraries\joomla\table\nested.php:346
Stack trace:
#0 C:\xampp\htdocs\joomla-cms-staging\libraries\joomla\table\nested.php(843): JTableNested->moveByReference(489, 'last-child', '489', false)
#1 C:\xampp\htdocs\joomla-cms-staging\libraries\legacy\table\menu.php(267): JTableNested->store(false)
#2 C:\xampp\htdocs\joomla-cms-staging\administrator\components\com_menus\models\item.php(453): JTableMenu->store()
#3 C:\xampp\htdocs\joomla-cms-staging\libraries\legacy\model\admin.php(248): MenusModelItem->batchMove('admin1.489', Array, Array)
#4 C:\xampp\htdocs\joomla-cms-staging\libraries\legacy\controller\form.php(274): JModelAdmin->batch(Array, Array, Array)
#5 C:\xampp\htdocs\joomla-cms-staging\administrator\components\com_menus\controllers\item.php(145): JControllerForm->batch(Object(MenusModelItem))
#6 C:\xampp\htdocs\joomla-cms-staging\libraries\legacy\controller\legacy.php(709): MenusControllerItem->batch()
#7 C:\xampp\htdocs\joomla-cms-staging\administrator\components\com_menus\menus.php(18): JControllerLegacy->execute('batch')
#8 C:\xampp\htdocs\joomla-cms-staging\libraries\cms\component\helper.php(394): require_once('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\joomla-cms-staging\libraries\cms\component\helper.php(369): JComponentHelper::executeComponent('C:\\xampp\\htdocs...')
#10 C:\xampp\htdocs\joomla-cms-staging\libraries\cms\application\administrator.php(98): JComponentHelper::renderComponent('com_menus')
#11 C:\xampp\htdocs\joomla-cms-staging\libraries\cms\application\administrator.php(156): JApplicationAdministrator->dispatch()
#12 C:\xampp\htdocs\joomla-cms-staging\libraries\cms\application\cms.php(265): JApplicationAdministrator->doExecute()
#13 C:\xampp\htdocs\joomla-cms-staging\administrator\index.php(51): JApplicationCms->execute()
#14 {main}
```
### Additional comments
Latest staging version

**Comment by Quy** [comment]
PR #15152
