### ISSUE TITLE
Joomla 3.7 breaks Akeeba Backup 5.3.1

### ISSUE THREAD

**Issue by udf2457** [joomla/joomla-cms#15603]
Run the Akeeba Backup Professional script:
```
www/cli/akeeba-backup.php --quiet
```

It throws the following:

```********** ERROR! **********

Call to a member function get() on null

Technical information:

Code: 0
File: /home/MYSITE/public_html/libraries/joomla/session/handler/joomla.php
Line: 71

Stack Trace:

#0 /home/MYSITE/public_html/libraries/joomla/session/session.php(648): JSessionHandlerJoomla->start()
#1 /home/MYSITE/public_html/libraries/joomla/session/session.php(608): JSession->_start()
#2 /home/MYSITE/public_html/libraries/joomla/session/session.php(486): JSession->start()
#3 /home/MYSITE/public_html/libraries/joomla/factory.php(236): JSession->get('user')
#4 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupPlatform/Joomla3x/Platform.php(365): JFactory::getUser()
#5 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Platform.php(272): Akeeba\Engine\Platform\Joomla3x->get_local_timestamp('Ymd')
#6 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Util/FileSystem.php(145): Akeeba\Engine\Platform->__call('get_local_times...', Array)
#7 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Util/FileSystem.php(174): Akeeba\Engine\Util\FileSystem->get_archive_name_variables()
#8 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Core/Domain/Init.php(446): Akeeba\Engine\Util\FileSystem->replace_archive_name_variables('site-[HOST]-[DA...')
#9 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Core/Domain/Init.php(264): Akeeba\Engine\Core\Domain\Init->getArchiveName()
#10 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Base/Part.php(255): Akeeba\Engine\Core\Domain\Init->_run()
#11 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Core/Kettenrad.php(314): Akeeba\Engine\Base\Part->tick()
#12 /home/MYSITE/public_html/administrator/components/com_akeeba/BackupEngine/Base/Part.php(259): Akeeba\Engine\Core\Kettenrad->_run()
#13 /home/MYSITE/public_html/administrator/components/com_akeeba/Model/Backup.php(217): Akeeba\Engine\Base\Part->tick()
#14 /home/MYSITE/public_html/cli/akeeba-backup.php(239): Akeeba\Backup\Admin\Model\Backup->startBackup(Array)
#15 /home/MYSITE/public_html/cli/akeeba-backup.php(428): AkeebaBackupCLI->execute()
#16 {main}
```

**Comment by nzampella** [comment]
J! 3.7 also breaks CRON jobs for CiviCRM:

PHP Fatal error:  Call to a member function get() on null in /home/nwtaadmin/public_html/libraries/joomla/session/handler/joomla.php on line 71
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15603">issues.joomla.org/tracker/joomla-cms/15603</a>.</sub>

**Comment by nzampella** [comment]
FWIW ... Nicolas is creating a work around for Akeeba backup cli jobs.  I only hope that I can use it to get the CiviCRM job running.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15603">issues.joomla.org/tracker/joomla-cms/15603</a>.</sub>

**Comment by mbabker** [comment]
For reference the only command line scripts that are affected are those which through some chain of events ends up calling `JFactory::getSession()`.  So not all CLI systems are broken (unfortunately none of the core CLI scripts have this kind of internal dependency).

Anywho, #15605 fixes this.  Closing in favor of the PR.
