### ISSUE TITLE
Jenkins build broken

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#16283]
![screen shot 2017-05-26 at 21 56 31](https://cloud.githubusercontent.com/assets/400092/26512408/511bcbb6-425e-11e7-80ed-78f066ba164b.png)

http://build.joomla.org/job/cms/

```
[CHECKSTYLE] Collecting checkstyle analysis files...
[CHECKSTYLE] Searching for all files in /var/lib/jenkins/jobs/cms/workspace that match the pattern build/logs/checkstyle.xml
[CHECKSTYLE] No files found. Configuration error?
[CHECKSTYLE] Computing warning deltas based on reference build #7807
[CHECKSTYLE] Plug-in Result: Success - no threshold has been exceeded
Recording test results
Publishing Clover coverage report...
Publishing Clover XML report...
Publishing Clover coverage results...
Pushing HEAD to branch master at repo origin
 > git --version # timeout=10
 > git push ssh://git@github.com/joomla/joomla-cms.git HEAD:master
ERROR: Failed to push branch master to origin
hudson.plugins.git.GitException: Command "git push ssh://git@github.com/joomla/joomla-cms.git HEAD:master" returned status code 1:
stdout: 
stderr: To ssh://git@github.com/joomla/joomla-cms.git
 ! [rejected]        HEAD -> master (non-fast-forward)
error: failed to push some refs to 'ssh://git@github.com/joomla/joomla-cms.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1877)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1596)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1951)
	at hudson.plugins.git.GitPublisher.perform(GitPublisher.java:328)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Build step 'Git Publisher' marked build as failure
Notifying endpoint 'HTTP:https://developer.joomla.org/glip/jenkins.php'
Finished: FAILURE
```

@mbabker @wilsonge ?

**Comment by mbabker** [comment]
Apparently https://github.com/joomla/joomla-cms/commit/cfb8cfd1c823f72b31aba4860cbf472502f4496d is in master but not staging and Jenkins is failing because it is behind master (when it never should be).

**Comment by PhilETaylor** [comment]
Apparently merged by @zero-24

**Comment by zero-24** [comment]
I have merged this commit into staging so something different happend with this commit after my merge.

**Comment by mbabker** [comment]
This has been sorted.

My guess is GitHub did something funny with it.  Because that PR says it was merged to staging, why it went to master is anybody's guess.
