### ISSUE TITLE
[4.0][com_media] On renaming image, a JS error is generated

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22797]
### Steps to reproduce the issue

Try to rename an image in Joomla admin -> Content -> media

### Expected result

No error, image renamed

### Actual result

```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at t.value (http://127.0.0.1/media/com_media/js/mediamanager.min.js:6:44919)
    at t.value (http://127.0.0.1/media/com_media/js/mediamanager.min.js:6:44664)
    at onSuccess (http://127.0.0.1/media/com_media/js/mediamanager.min.js:6:38223)
    at XMLHttpRequest.o.onreadystatechange (http://127.0.0.1/media/system/js/core.min.js?714bd7c681dcb1da83e738c93edacebc:1:8195)
```

<img width="1059" alt="screenshot 2018-10-23 at 22 22 48" src="https://user-images.githubusercontent.com/400092/47391623-326a2380-d712-11e8-8ceb-63298dfa7d7c.png">

### System information (as much as possible)

Google Chrome 70

**Comment by dgrammatiko** [comment]
This comes from the alert, https://github.com/joomla-projects/custom-elements/pull/104 needs to be reversed as it's totally wrong
