### ISSUE TITLE
Joomla! 4.0.0-alpha10 - Feed components and links generation

### ISSUE THREAD

**Issue by vintzl** [joomla/joomla-cms#25925]
With Joomla! 4.0.0-alpha10, when I visit these links 
- /?format=feed&type=atom
- /?format=feed&type=rss

### Expected result
Everything should be fine

### Actual result
I get this error, while visiting the above mentioned links, **_even with every Feeds components disabled_**:
```
<?xml version="1.0" encoding="UTF-8"?>
<error>
	<code>0</code>
	<message>Call to undefined method Joomla\Component\Content\Site\View\Featured\FeedView::escape()</message>
	<trace>#0 /home/www/libraries/src/MVC/Controller/BaseController.php(699): Joomla\Component\Content\Site\View\Featured\FeedView-&gt;display()
#1 /home/www/components/com_content/Controller/DisplayController.php(127): Joomla\CMS\MVC\Controller\BaseController-&gt;display(true, Array)
#2 /home/www/libraries/src/MVC/Controller/BaseController.php(737): Joomla\Component\Content\Site\Controller\DisplayController-&gt;display()
#3 /home/www/libraries/src/Dispatcher/ComponentDispatcher.php(146): Joomla\CMS\MVC\Controller\BaseController-&gt;execute('display')
#4 /home/www/components/com_content/Dispatcher/Dispatcher.php(55): Joomla\CMS\Dispatcher\ComponentDispatcher-&gt;dispatch()
#5 /home/www/libraries/src/Component/ComponentHelper.php(383): Joomla\Component\Content\Site\Dispatcher\Dispatcher-&gt;dispatch()
#6 /home/www/libraries/src/Application/SiteApplication.php(205): Joomla\CMS\Component\ComponentHelper::renderComponent('com_content')
#7 /home/www/libraries/src/Application/SiteApplication.php(244): Joomla\CMS\Application\SiteApplication-&gt;dispatch()
#8 /home/www/libraries/src/Application/CMSApplication.php(241): Joomla\CMS\Application\SiteApplication-&gt;doExecute()
#9 /home/www/includes/app.php(63): Joomla\CMS\Application\CMSApplication-&gt;execute()
#10 /home/www/index.php(36): require_once('/home/www/...')
#11 {main}</trace>
</error>
```

### System information (as much as possible)
- Debian sid x64
- php7.3
- mariadb-server-10.3

### Additional comments
As an aside, even with every Feeds components, disabled, links from `JFactory::getDocument()->_links` will still be generated…

**Comment by SharkyKZ** [comment]
There's PR #24028 ready to commit.

**Comment by zero-24** [comment]
Closing as there is a PR to be merged already. Thanks! :)
