### ISSUE TITLE
[4.0] npm failure

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28450]
Running npm ci today is failing

I have traced it down to the last part of the scripts
> npm run build:com_media

The full trace is
```

> joomla@4.0.0 build:com_media C:\htdocs\joomla-cms
> cross-env NODE_ENV=production webpack --progress --hide-modules --config administrator/components/com_media/webpack.config.js

10% building 1/1 modules 0 active(node:64652) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
70% building 4/8 modules 4 active C:\htdocs\joomla-cms\administrator\components\com_media\node_modules\vue\dist\vue.esm.jsTypeError: dep.getResourceIdentifier is not a function
    at addDependency (C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:796:30)
    at iterationOfArrayCallback (C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:208:3)
    at addDependenciesBlock (C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:816:5)
    at Compilation.processModuleDependencies (C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:827:4)
    at afterBuild (C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:954:15)
    at C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:998:11
    at callback (C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:734:5)
    at C:\htdocs\joomla-cms\node_modules\webpack\lib\Compilation.js:782:12
    at handleParseResult (C:\htdocs\joomla-cms\node_modules\webpack\lib\NormalModule.js:478:12)
    at C:\htdocs\joomla-cms\node_modules\webpack\lib\NormalModule.js:500:6
    at C:\htdocs\joomla-cms\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\htdocs\joomla-cms\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\htdocs\joomla-cms\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\htdocs\joomla-cms\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\htdocs\joomla-cms\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\htdocs\joomla-cms\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\htdocs\joomla-cms\node_modules\babel-loader\lib\index.js:55:71
70% building 7/8 modules 1 active ...\sass-loader\lib\loader.js!C:\htdocs\joomla-cms\administrator\components\com_media\resources\styles\mediamanager.scss C
:\htdocs\joomla-cms\node_modules\webpack\node_modules\neo-async\async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (C:\htdocs\joomla-cms\node_modules\webpack\node_modules\neo-async\async.js:16:11)
    at C:\htdocs\joomla-cms\node_modules\webpack\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! joomla@4.0.0 build:com_media: `cross-env NODE_ENV=production webpack --progress --hide-modules --config administrator/components/com_media/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the joomla@4.0.0 build:com_media script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brian\AppData\Roaming\npm-cache\_logs\2020-03-25T12_37_17_945Z-debug.log

```

**Comment by jwaisner** [comment]
I was able to complete a successful `npm ci` with no issues. I also attempted `npm run build:com_media` with no errors. I am using NPM 6.4.1.

**Comment by wilsonge** [comment]
I can run successfully too on OSX - @jwaisner what's your OS?

**Comment by jwaisner** [comment]
Windows 10

**Comment by Quy** [comment]
No errors on Windows 10.

**Comment by jwaisner** [comment]
@brianteeman can you provide the OS you are using? So far of those that have tested no issues can be found. I would also recommend a hard reset of the files from Github just to make sure the files are clean.

**Comment by brianteeman** [comment]
I found the problem. recently we changed the way that com_media is built. once I removed the now unused (and conflicting) com_media/node_modules I was able to rebuild
