### ISSUE TITLE
[4.0] Building npm fails on my macbook :( 

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#28556]
### Steps to reproduce the issue
Currently npm hangs during building media manager on my Macbook. Console output below:

```
> joomla@4.0.0 build:com_media /Users/george/Sites/joomla-cms
> cross-env NODE_ENV=production webpack --progress --hide-modules --config administrator/components/com_media/webpack.config.js

10% building 1/1 modules 0 active(node:4981) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
70% building 6/8 modules 2 active .../Sites/joomla-cms/administrator/components/com_media/node_modules/vue/dist/vue.esm.jsTypeError: dep.getResourceIdentifier is not a function
    at addDependency (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:796:30)
    at iterationOfArrayCallback (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:208:3)
    at addDependenciesBlock (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:816:5)
    at Compilation.processModuleDependencies (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:827:4)
    at afterBuild (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:954:15)
    at buildModule.err (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:998:11)
    at callback (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:734:5)
    at module.build.error (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/Compilation.js:782:12)
    at handleParseResult (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/NormalModule.js:478:12)
    at doBuild.err (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/NormalModule.js:500:6)
    at runLoaders (/Users/george/Sites/joomla-cms/node_modules/webpack/lib/NormalModule.js:358:12)
    at /Users/george/Sites/joomla-cms/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/george/Sites/joomla-cms/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/george/Sites/joomla-cms/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/george/Sites/joomla-cms/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/george/Sites/joomla-cms/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at loader.call.then.args (/Users/george/Sites/joomla-cms/node_modules/babel-loader/lib/index.js:59:71)
70% building 125/128 modules 3 active /Users/george/Sites/joomla-cms/node_modules/file-saver/src/FileSaver.js/Users/george/Sites/joomla-cms/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/george/Sites/joomla-cms/node_modules/neo-async/async.js:16:11)
    at /Users/george/Sites/joomla-cms/node_modules/neo-async/async.js:2818:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

After this it hangs until you force quit the command with cmd+c

### System information (as much as possible)
```
$ node --version 
v10.15.3
```
```
$ npm --version
6.14.2
```

**Comment by wilsonge** [comment]
@C-Lodder any ideas - assuming this has come from the dependency updates. clearly things work in travis.

**Comment by wilsonge** [comment]
Seems related https://github.com/webpack-contrib/mini-css-extract-plugin/issues/489 - although we don't use the html webpack plugin - but presumably something similar

**Comment by C-Lodder** [comment]
I'll have to have a look. After updating my deps locally, I had no issue with several attempts at running `npm i`.

If you're running `ci`, try `i` instead

**Comment by wilsonge** [comment]
Ugh so apparently testing an older PR left me with files in the old com_media node_modules location. Cleared them out and it's all fixed itself. No clue why the old node_modules directory causes issues but....

**Comment by C-Lodder** [comment]
Do you want me to add a temporary script to delete the com_media node_modules directory? Maybe keep it in the repo for a month or two.

**Comment by wilsonge** [comment]
Nah it's fine. It will clear itself out. plus a month won't be enough. we still have open pr's from 2016 😆

**Comment by brianteeman** [comment]
@wilsonge I had the exact same problem the other day

**Comment by wilsonge** [comment]
I saw it. As soon as I saw the directory I remembered your issue - that's what prompted me to clear it - my `jinstall` alias used to clear it but i got rid of it a while ago
