### ISSUE TITLE
[4.0] npm install and npm ci errors

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#31114]
### Steps to reproduce the issue
I cloned the joomla repo and switched to 4.0-dev.
Running `npm install` or `npm ci` gives me an error.

### Expected result
Success

### Actual result
```
> node build.js --copy-assets && node build.js --build-pages

/var/www/html/joomla-dev/joomla-cms/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/joomla-dev/joomla-cms/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```

### System information (as much as possible)
Joomla 4.0, php 7.3

**Comment by dgrammatiko** [comment]
@sakiss what's your OS?
What's the output of `node -v`?
what's the output of `npm -v`?

**Comment by sakiss** [comment]
Ubuntu 16.04
8.17.0
6.13.4

**Comment by dgrammatiko** [comment]
You need node > v10  https://github.com/joomla/joomla-cms/blob/5813af58abdc61c8c71bcdf4302d5a0bb1b505b3/package.json#L11. https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

**Comment by sakiss** [comment]
That's it.
Thank you @dgrammatiko !
