### ISSUE TITLE
New folder com_media/resources/ is absent from Joomla_4.2.6 and Joomla_4.2.7-dev

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#39448]
New folder administrator/components/com_media/resources/ is not present in:

Joomla_4.2.6-Stable-Full_Package
Joomla_4.2.7-dev-Development-Full_Package (last nightly: Monday, 19 December )

I would not have referred to 4.2.6 version if the reference to this folder was not present in its media.xml file
Found this while dabbling with npm ci and sass compiler.
But I guess it happened while building the latest packages because /resources/ is present in former packages.

```
Error: Could not resolve entry module (administrator/components/com_media/resources/scripts/mediamanager.es6.js).
    at error (/xxx/xxx/xxx/htdocs/426_stable/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.loadEntryModule (/xxx/xxx/axxx/htdocs/426_stable/node_modules/rollup/dist/shared/rollup.js:22400:20)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}

npm ERR! code 255
npm ERR! path /xxx/xxx/htdocs/426_stable
npm ERR! command failed
npm ERR! command sh -c -- node build/build.js --prepare
```

**Comment by ghazal** [comment]
> I am not sure if I understand you right. You want to run npm ci on a normal Joomla installation, not on a git clone of the Joomla repository?

Absolutely.
I wanted to test if it was feasible and it is, once node and npm are installed on the computer.
But my goal is actually to add relevant corrections to the article about ["SCSS and Sass"](https://docs.joomla.org/J4.x:SCSS_and_Sass) in Joomla Documentation where there are some errors and is impossible to implement as is. Just read the first few lines and you'll see.

But this is not the issue here, it being the missing folder /resources/ in the most recent iteration of joomla packages, in accordance with the .xml file of com_media.

**Comment by dgrammatiko** [comment]
@richard67 he's right on the fact that the Media manager  JS source is **NOT** in the `build/media_source` and it probably should be.

>But this is not the issue here, it being the missing folder /resources/ in the most recent iteration of joomla packages, in accordance with the .xml file of com_media.

@ghazal joomla will (probably) never ship the resources folder. Also what you're trying to do is not something that the tools were designed for (I know, I wrote them) and even if they work it's definitely not something that should be promoted (nobody is testing this case and it might break at any point)

**Comment by richard67** [comment]
@dgrammatiko So what shall we do with this issue?

**Comment by dgrammatiko** [comment]
@richard67 I have no clue, it seems that the resources folder is shipping with the distributable which odd as it's the only source JS that is distributed. Also questionable why? I don't have any answers here 🤷‍♂️

**Comment by richard67** [comment]
I also have no idea why that folder is shipped.
