### ISSUE TITLE
Internal server error when choosing an image

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#43510]
### Steps to reproduce the issue
Internal server error when choosing an image

Create or edit an article,
go to "images and links", then "select" and choose any (here screenshot: image. https://prnt.sc/zJZPZ942QT_e )
Confirm your selection by clicking on "select" https://prnt.sc/o_cqYpBezrEe
The message "internal server error" will appear (here screenshot: https://prnt.sc/Uy8zXKfMXvNz )

### Expected result
setting the chosen image with the URL of the image in question.

### Actual result
"Internal server error" message

### System information (as much as possible)
Joomla 5.1.0
PHP 8.1.28
db MySql 10.6.17-MariaDB-cll-lve

**Comment by ivanti** [comment]
I have the same problem. Here last log from everything.php:

2024-05-22T10:40:52+00:00	CRITICAL XXX.XXX.XXX.XXX	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Pagina non trovata". Stack trace: #0 [ROOT]/libraries/src/Application/SiteApplication.php(754): Joomla\CMS\Router\Router->parse()
#1 [ROOT]/libraries/src/Application/SiteApplication.php(244): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(306): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(58): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('/home/xxxxxxxx/...')
#5 {main}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by hellowebcoder73** [comment]
I have absolutely the same problem at two websites on two different server since 17th of May. "Internal Server Error" when trying to select intro image or trying to insert image into an Article or Category. Before 17th of May both of them worked without any problem. There was not any changes on the websites (nor Joomla/Component update nor any new plugin/component install nor any server update or setting changes)
Joomla 5.1
php 8.1 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by drmenzelit** [comment]
Do you see something like that in the browser console?
![grafik](https://github.com/joomla/joomla-cms/assets/9153168/76311a46-567d-48ad-995d-bbe5a6558f75)

Where are the websites hosted? Some special rules in Apache mod_security?

**Comment by galamarco** [comment]
Hi drmenzelit,
I'm sorry but the image you wanted to post is not visible. Can you post it again?
My sites are hosted on SuppotHost dot com
Regarding your question "Some special rules in Apache mod_security?" How can I check it to reply to you?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by galamarco** [comment]
looking at the console while I try to select an image I get this error.


(anonime)	@	joomla-media-select.min.js?a034d4:27
Joomla.getMedia	@	joomla-media-select.min.js?a034d4:27
modalClose	@	joomla-field-media.min.js?d823e5:4
onClick	@	joomla-field-media.min.js?d823e5:4
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by joomdonation** [comment]
@galamarco One of our customer had the similar issue. He said disable the rule `ModSecurity: collections_remove_stale`  from mod_security and the error is gone.

You should contact your hosting provider, ask them to do the same for your hosting account. It might/should solve the issue.

**Comment by galamarco** [comment]
sorry here a full version of the error:

joomla-media-select.min.js?a034d4:27   
         GET https://www.webg.it/administrator/index.php?option=com_media&format=json&task=api.files&url=true&path=local-images%3A%2Fpowered_by.png&mediatypes=0%2C1%2C2%2C3&9c8a05836aed9771fb4067c966f172f6=1 403 (Forbidden)

(anonime)	@	joomla-media-select.min.js?a034d4:27
Joomla.getMedia	@	joomla-media-select.min.js?a034d4:27
modalClose	@	joomla-field-media.min.js?d823e5:4
onClick	@	joomla-field-media.min.js?d823e5:4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by om615** [comment]
I had exactly the same error with two joomla pages. One is version 4.4.4, the other is version 5.1. The two websites are on two different servers.

**Comment by galamarco** [comment]
@ivanti @ciaowebcoder73 @om615 please vote for this problem at the top right by ticking "I have encountered this problem" and indicating the importance you attribute to it. This way it gets the right priority. ^_^<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by ivanti** [comment]
@galamarco I already did it.

From my console:

joomla-media-select.js?a034d4:313 
 
GET https://********/administrator/index.php?option=com_media&format=json&t…laceholder.png&mediatypes=0%2C1%2C2%2C3&40997ef…=1 404 (Not Found)
(anonimo)	@	joomla-media-select.js?a034d4:313
Joomla.getMedia	@	joomla-media-select.js?a034d4:294
modalClose	@	joomla-field-media.js?d823e5:188
onClick	@	joomla-field-media.js?d823e5:162<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by ivanti** [comment]
The problem is only present from backend, while from frontend I can select images regularly via the modal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by galamarco** [comment]
While waiting for a structural solution, I share that thanks to @joomdonation it has emerged that disabling ModSecurity from cPanel (or via your hosting) solves the problem. 
However, disabling ModSecurity is certainly not the optimal solution, on the contrary, it exposes the site to more frequent attacks. 
This is why we are waiting for a better solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by joomdonation** [comment]
@galamarco You should not have to disable ModSecurity  completely, just disable the mentioned rule **collections_remove_stale** should be enough.

**Comment by PixedBo** [comment]
Same error here in a Joomla4 and Joomla 5 webistes with CPANEL. Image selection stop working a few days ago out of nothing. Can this be related to a Cpanel update? Anyway i've contacted my hosting provider to disable the rule mentioned by @joomdonation 
Thanks

**Comment by galamarco** [comment]
@drmenzelit ti confermo che vedo degli errori:
![image](https://github.com/joomla/joomla-cms/assets/5132398/1b512ede-fa73-4788-883a-adb7e5000c6e)

Here an example URL of first error "Failed to load resource: the server responded with a status of 403 ()":
 [...] /administrator/index.php?option=com_media&format=json&task=api.files&url=true&path=local-images%3A%2Fjoomla_logo_black.jpg&mediatypes=0%2C1%2C2%2C3&a5898cd90037069bb26396fe08c96301=1

@joomdonation I discussed your proposal with the hosting but they tell me that for shared servers, disabling mentionedcollection_remove_stale is not an applicable solution. It would also affect other customers.

**Comment by channingb** [comment]
We are having the same issue.  The hosting company heightened security last week due to "a huge rash of bot attacks against WHMCS systems".  

We get the similar php errors, "page not found" (see below).  It occurs doing many different tasks.  Convert Forms component does not show the full form builder, adding an image using JCE Editor in article manager will fail to save but does not seem to break in YTP Page builder, cannot save in styles or other YTP builder areas, adding image in JSitemap failed, etc. 

We have done quite a bit of white listing which is not ideal.  Today, the host whitelisted 941100 and 941160.  Both, they said, are there to protect against XSS attacks.



2024-08-16T18:10:15+00:00	CRITICAL 149.106.104.144	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page not found". Stack trace: #0 [ROOT]/libraries/src/Application/SiteApplication.php(746): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]/libraries/src/Application/SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('/home/fullcirc/...')
#5 {main}

Thank you.

**Comment by timlg07** [comment]
Any news on this? It recently started to happen for us, while everything was working fine a few months ago. Maybe due to a Joomla update? The page currently runs on 5.3.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43510">issues.joomla.org/tracker/joomla-cms/43510</a>.</sub>

**Comment by MacJoom** [comment]
Thank you for contribution. We have to close this issue as this cannot be fixed by Joomla itself, but must be done by disabling the rule 'collections_remove_stale' in mod_security - possibly by the hosting service.
