### ISSUE TITLE
Joomla 5.1.2 - Web Cron does not execute scheduled tasks.

### ISSUE THREAD

**Issue by J-Wick4** [joomla/joomla-cms#43903]
### Steps to reproduce the issue

- Disabled Lazy loader.
- Enabled Web Cron, generated hashed URL, saved.
- Set up a task to execute every minute.
- Setup a cron entry to fetch the hashed URL produced by Joomla to run every minute.

### Expected result
Fetch the Web Cron URL with system cron every minute and have scheduled tasks executed based on their interval settings.

### Actual result
Cron reported success, but no tasks were ever executed.

The first time accessing the web cron URL in a browser, this log is produced, then never again on subsequent reloads. Is this an error of the URL Rewrites function or a lack of a menu item?

2024-08-11T04:01:37+00:00       CRITICAL 206.45.15.244  error   Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page not found". Stack trace: #0 [ROOT]/libraries/src/Application/SiteApplication.php(754): Joomla\CMS\Router\Router->parse()
#1 [ROOT]/libraries/src/Application/SiteApplication.php(244): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(306): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(58): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('...')
#5 {main}

### System information (as much as possible)

Joomla 5.1.2
PHP 8.3.10
Apache w/ FPM
MariaDB 10.6.19
Rocky Linux 8.6
Plesk Obsidian 18.0.62
Cloudflare Pro

### Additional comments

I got the scheduled tasks running by using the cli/joom.php method using cron, which, in reality, is a better and more secure method. However, using this method required me to program additional code to generate logs, whereas when using the "Run Test" button of the task, it generates logs the usual Joomla way.

**Comment by richard67** [comment]
> Setup a cron entry to fetch the hashed URL produced by Joomla to run every minute.

@J-Wick4 This step is not 100% clear to me. How and where do you set up the cron entry to fetch the trigger (hashed) URL?
- A web cron job e.g. like some providers allow to do in their control panel?
- A real Unix cron job doing using e.g. curl?
Could you provide details on that?

Besides that, the issue could be similar or related to what is handled with PRs #43817 and #43164 .

**Comment by richard67** [comment]
@J-Wick4 Could you test if this pull request solves your issue? https://github.com/joomla/joomla-cms/pull/43817

**Comment by Hackwar** [comment]
Can you please check if this is solved with 5.2?

**Comment by adoucette** [comment]
The web cron URL provided by Joomla in Global Configuration --> Scheduled Tasks --> Web Cron --> Web Cron Link (base) is not correct.
The folder path is not correct (should have an "s" on end of "/component" and there is no "ajax" subfolder in the "components" folder.
An example of what's currently generated: (as of Joomla 5.2.5)
https://mywebsite.com/component/ajax/?plugin=RunSchedulerWebcron&group=system&format=json&hash=123abc456def789gh

However, the tasks can be successfully run by cron with: ([credit](https://forum.joomla.org/viewtopic.php?p=3742509#p3742452 "credit"))
php /path/to/joomla/cli/joomla.php scheduler: run
Credit
Above is in Joomla documentation for the cli, but not mentioned in the scheduled tasks documentation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43903">issues.joomla.org/tracker/joomla-cms/43903</a>.</sub>

**Comment by richard67** [comment]
@adoucette The "component/ajax" in the URL does not belong to real folders. The router in Joomla uses that to resolve the component ("ajax" in this case), and the options are passed to that component via the URL parameters.

@Hackwar may correct me if I'm wrong.

**Comment by brianteeman** [comment]
@adoucette you are confusing file paths and urls
