### ISSUE TITLE
Update issue with 3.5B2 and PHP7

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#9074]
The following was a preliminary test of an existing 3.4.8 site with out-of-date extensions upgraded to 3.5B2 and PHP7

After the update to 3.5B2 and PHP7, an out of date component notice was given for several extensions.
During the update the following error occurred.
```
Warning: Parameter 1 to PlgSystemRedirect::handleError() expected to be a reference, value given in Unknown on line 0
```
```
Fatal error: Uncaught Error: Call to a member function add() on null in /libraries/joomla/cache/storage/memcache.php:466
Stack trace:
#0 /libraries/joomla/cache/storage/memcache.php(287): JCacheStorageMemcache->lockindex()
#1 /libraries/joomla/cache/cache.php(292): JCacheStorageMemcache->clean('_system', 'group')
#2 /libraries/joomla/cache/controller.php(69): JCache->clean('_system')
#3 /tmp/install_56b39e729e97f/install.php(99): JCacheController->__call('clean', Array)
#4 /libraries/cms/installer/adapter/package.php(423): Pkg_Gantry5InstallerScript->postflight('update', Object(JInstallerAdapterPackage), Array)
#5 /libraries/cms/installer/adapt in /libraries/joomla/cache/storage/memcache.php on line 466
```
Note: cross posted with Gantry 5 https://github.com/gantry/gantry5/issues/1133

**Comment by photodude** [comment]
As I have browsed the site to check things I have found that this occurs with many extensions Looks like it is possibly a Joomla issue
```
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: PHP Warning:  Parameter 1 to PlgSystemRedirect::handleError() expected to be a reference, value given in Unknown on line 0
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function add() on null in /libraries/joomla/cache/storage/memcache.php:466
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: Stack trace:
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: #0 /libraries/joomla/cache/storage/memcache.php(287): JCacheStorageMemcache->lockindex()
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: #1 /libraries/joomla/cache/cache.php(292): JCacheStorageMemcache->clean('com_plugins', 'group')
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: #2 /libraries/joomla/cache/controller.php(69): JCache->clean()
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: #3 /libraries/f0f/utils/cache/cleaner.php(76): JCacheController->__call('clean', Array)
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: #4 /libraries/f0f/utils/cache/cleaner.php(36): F0FUtilsCacheCleaner::clearCacheGroups(Array, Array)
[Thu Feb 04 14:01:55 2016] [warn]  mod_fcgid: stderr: #5 /plugins/quickicon/akeebabackup/akeebabackup.php(53): F0FUtilsCacheCleaner::cle in /libraries/joomla/cache/storage/memcache.php on line 466
```

```
Warning: Parameter 1 to PlgSystemRedirect::handleError() expected to be a reference, value given in Unknown on line 0
```
```
Fatal error: Uncaught Error: Call to a member function add() on null in /libraries/joomla/cache/storage/memcache.php:466
Stack trace:
#0 /libraries/joomla/cache/storage/memcache.php(287): JCacheStorageMemcache->lockindex()
#1 /libraries/joomla/cache/cache.php(292): JCacheStorageMemcache->clean('com_rsform', 'group')
#2 /libraries/joomla/cache/controller.php(69): JCache->clean()
#3 /administrator/components/com_rsform/helpers/rsform.php(25): JCacheController->__call('clean', Array)
#4 /administrator/components/com_rsform/rsform.php(22): require_once('/mnt/data/vhost...')
#5 /libraries/cms/component/helper.php(402): require_once('/mnt/data/vhost. in /libraries/joomla/cache/storage/memcache.php on line 466****
```

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/blob/3.5.0-beta2/plugins/system/redirect/redirect.php#L55 should not be receiving its parameter by reference, signature should match [JErrorPage::render()](https://github.com/joomla/joomla-cms/blob/3.5.0-beta2/libraries/cms/error/page.php) (though the plugin's method shouldn't need to be aware of Throwables).  Though the method it calls if it's not handling 404's, [JError::customErrorPage()](https://github.com/joomla/joomla-cms/blob/3.5.0-beta2/libraries/legacy/error/error.php#L773) probably should be made aware of Throwables similar to `JErrorPage` (or even better just proxy to that class instead).

**Comment by brianteeman** [comment]
Can you retest with beta 3 please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9074">issues.joomla.org/joomla-cms/9074</a>.</sub>

**Comment by brianteeman** [comment]
Please see #9270<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9074">issues.joomla.org/joomla-cms/9074</a>.</sub>
